#文件上传路径
web:
  basePath: D:\\java\\IdeaProjects\\acefet\\blog\\client\\
  #WEB-INF\\classes\\templates\\static\\attachments\\
  attachments: target\\classes\\static\\assets\\attachments\\
  attPath: ../assets/attachments/
spring:
    config:
      name: blog-server
    mvc:
      throw-exception-if-no-handler-found: true
    resources:
      add-mappings: false
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      username: blog
      password: blog
      url: jdbc:mysql://www:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect