spring:
  config:
    name: blog-common
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: blog
    password: blog
    url: jdbc:mysql://www:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect